export const INDUSTRY_LIST = [
  {
    id: 1,
    title: 'ソフトウエア・通信業',
    sector_id: 0,
    sector_title: '選択なし',
  },
  {
    id: 1,
    title: 'ソフトウエア・通信業',
    sector_id: 1,
    sector_title: 'IT・通信',
  },
  {
    id: 1,
    title: 'ソフトウエア・通信業',
    sector_id: 2,
    sector_title: 'ソフトウェア情報処理',
  },
  {
    id: 1,
    title: 'ソフトウエア・通信業',
    sector_id: 3,
    sector_title: 'インターネット関連・ゲーム・アプリ関連',
  },
  { id: 2, title: 'メーカー', sector_id: 0, sector_title: '選択なし' },
  {
    id: 2,
    title: 'メーカー',
    sector_id: 1,
    sector_title: '機械・産業用装置・電機・OA機器',
  },
  {
    id: 2,
    title: 'メーカー',
    sector_id: 2,
    sector_title: '自動車・自動車部品・輸送用機器',
  },
  {
    id: 2,
    title: 'メーカー',
    sector_id: 3,
    sector_title: 'コンピュータ・通信機器・精密機器',
  },
  { id: 2, title: 'メーカー', sector_id: 4, sector_title: '電子部品・半導体' },
  {
    id: 2,
    title: 'メーカー',
    sector_id: 5,
    sector_title: '食品・飲料・たばこ・飼料',
  },
  {
    id: 2,
    title: 'メーカー',
    sector_id: 6,
    sector_title: '化学・医薬・化粧品',
  },
  {
    id: 2,
    title: 'メーカー',
    sector_id: 7,
    sector_title: '鉄鋼・非鉄金属・金属製品',
  },
  {
    id: 2,
    title: 'メーカー',
    sector_id: 8,
    sector_title: '石油・石炭・ゴム・プラスチック',
  },
  {
    id: 2,
    title: 'メーカー',
    sector_id: 9,
    sector_title: 'ガラス・セラミック・セメント',
  },
  {
    id: 2,
    title: 'メーカー',
    sector_id: 10,
    sector_title: 'パルプ・紙・紙加工・印刷・印刷関連',
  },
  {
    id: 2,
    title: 'メーカー',
    sector_id: 11,
    sector_title: '日用品・文具・オフィス用品',
  },
  {
    id: 2,
    title: 'メーカー',
    sector_id: 12,
    sector_title: '建材・エクステリア',
  },
  {
    id: 2,
    title: 'メーカー',
    sector_id: 13,
    sector_title: 'インテリア・住宅関連',
  },
  {
    id: 2,
    title: 'メーカー',
    sector_id: 14,
    sector_title: 'アパレル・服飾関連',
  },
  {
    id: 2,
    title: 'メーカー',
    sector_id: 15,
    sector_title: 'スポーツ・玩具・ゲーム機器',
  },
  {
    id: 2,
    title: 'メーカー',
    sector_id: 16,
    sector_title: 'その他メーカー・製造関連',
  },
  { id: 3, title: 'エネルギー配給業', sector_id: 0, sector_title: '選択なし' },
  {
    id: 3,
    title: 'エネルギー配給業',
    sector_id: 1,
    sector_title: '電気・ガス・石油・水道',
  },
  {
    id: 4,
    title: '広告・出版・マスコミ',
    sector_id: 0,
    sector_title: '選択なし',
  },
  {
    id: 4,
    title: '広告・出版・マスコミ',
    sector_id: 1,
    sector_title: '放送（テレビ・ラジオ含む）',
  },
  {
    id: 4,
    title: '広告・出版・マスコミ',
    sector_id: 2,
    sector_title: '新聞・出版',
  },
  { id: 4, title: '広告・出版・マスコミ', sector_id: 3, sector_title: '広告' },
  {
    id: 4,
    title: '広告・出版・マスコミ',
    sector_id: 4,
    sector_title: 'その他（芸能・エンタテインメント関連等）',
  },
  { id: 5, title: '運輸業', sector_id: 0, sector_title: '選択なし' },
  {
    id: 5,
    title: '運輸業',
    sector_id: 1,
    sector_title: '運輸（鉄道・航空・海運・物流等）',
  },
  { id: 6, title: '商社・卸売業', sector_id: 0, sector_title: '選択なし' },
  { id: 6, title: '商社・卸売業', sector_id: 1, sector_title: '総合商社' },
  { id: 6, title: '商社・卸売業', sector_id: 2, sector_title: '専門商社' },
  { id: 7, title: '流通・小売', sector_id: 0, sector_title: '選択なし' },
  {
    id: 7,
    title: '流通・小売',
    sector_id: 1,
    sector_title: '百貨店・スーパー・ドラッグストア・コンビニ・ホームセンター',
  },
  {
    id: 7,
    title: '流通・小売',
    sector_id: 2,
    sector_title: '通信販売・専門店・その他小売り',
  },
  { id: 8, title: '金融・保険業', sector_id: 0, sector_title: '選択なし' },
  {
    id: 8,
    title: '金融・保険業',
    sector_id: 1,
    sector_title: '銀行（共同組織金融含む）',
  },
  { id: 8, title: '金融・保険業', sector_id: 2, sector_title: '証券' },
  { id: 8, title: '金融・保険業', sector_id: 3, sector_title: '保険' },
  {
    id: 8,
    title: '金融・保険業',
    sector_id: 4,
    sector_title: 'その他金融（クレジット等）',
  },
  {
    id: 8,
    title: '金融・保険業',
    sector_id: 5,
    sector_title: 'リース・レンタル',
  },
  { id: 9, title: '不動産・建設業', sector_id: 0, sector_title: '選択なし' },
  {
    id: 9,
    title: '不動産・建設業',
    sector_id: 1,
    sector_title: 'ディベロッパー',
  },
  {
    id: 9,
    title: '不動産・建設業',
    sector_id: 2,
    sector_title: '建設・建築設計・ハウスメーカー',
  },
  { id: 9, title: '不動産・建設業', sector_id: 3, sector_title: '設備関連' },
  {
    id: 9,
    title: '不動産・建設業',
    sector_id: 4,
    sector_title: 'プラント・プラントエンジニアリング',
  },
  {
    id: 9,
    title: '不動産・建設業',
    sector_id: 5,
    sector_title: '不動産取引・不動産賃貸・不動産管理',
  },
  {
    id: 10,
    title: '専門・技術サービス業',
    sector_id: 0,
    sector_title: '選択なし',
  },
  {
    id: 10,
    title: '専門・技術サービス業',
    sector_id: 1,
    sector_title: 'デザイン・芸術関連',
  },
  {
    id: 10,
    title: '専門・技術サービス業',
    sector_id: 2,
    sector_title: 'コンサルティング・マーケティング・調査',
  },
  {
    id: 10,
    title: '専門・技術サービス業',
    sector_id: 3,
    sector_title: 'その他専門・技術サービス',
  },
  { id: 11, title: 'ホテル・外食業', sector_id: 0, sector_title: '選択なし' },
  {
    id: 11,
    title: 'ホテル・外食業',
    sector_id: 1,
    sector_title: 'ホテル・旅館',
  },
  { id: 11, title: 'ホテル・外食業', sector_id: 2, sector_title: '外食' },
  {
    id: 11,
    title: 'ホテル・外食業',
    sector_id: 3,
    sector_title: 'その他フード',
  },
  {
    id: 12,
    title: '生活関連サービス業',
    sector_id: 0,
    sector_title: '選択なし',
  },
  {
    id: 12,
    title: '生活関連サービス業',
    sector_id: 1,
    sector_title: '理美容・エステ・フィットネスクラブ',
  },
  {
    id: 12,
    title: '生活関連サービス業',
    sector_id: 2,
    sector_title: '旅行・観光',
  },
  {
    id: 12,
    title: '生活関連サービス業',
    sector_id: 3,
    sector_title: '家事サービス・クリーニング',
  },
  {
    id: 12,
    title: '生活関連サービス業',
    sector_id: 4,
    sector_title: '冠婚葬祭',
  },
  {
    id: 12,
    title: '生活関連サービス業',
    sector_id: 5,
    sector_title: 'その他生活関連サービス',
  },
  {
    id: 12,
    title: '生活関連サービス業',
    sector_id: 6,
    sector_title: 'アミューズメント・レジャーサービス',
  },
  { id: 13, title: '教育業', sector_id: 0, sector_title: '選択なし' },
  { id: 13, title: '教育業', sector_id: 1, sector_title: '教育関連' },
  { id: 14, title: '医療・福祉', sector_id: 0, sector_title: '選択なし' },
  {
    id: 14,
    title: '医療・福祉',
    sector_id: 1,
    sector_title: '医療・保育・介護・福祉',
  },
  { id: 15, title: 'サービス業', sector_id: 0, sector_title: '選択なし' },
  {
    id: 15,
    title: 'サービス業',
    sector_id: 1,
    sector_title: '環境・リサイクル・廃棄物処理',
  },
  { id: 15, title: 'サービス業', sector_id: 2, sector_title: '整備・修理' },
  { id: 15, title: 'サービス業', sector_id: 3, sector_title: '人材サービス' },
  {
    id: 15,
    title: 'サービス業',
    sector_id: 4,
    sector_title: 'その他事業サービス（警備、コールセンター等）',
  },
  { id: 16, title: 'その他', sector_id: 0, sector_title: '選択なし' },
  { id: 16, title: 'その他', sector_id: 1, sector_title: 'その他' },
];
