export const STYLE_VARIABLES = {
  FONT_FAMILY: "'Noto Sans Jp', sans-serif",
  FONT_SECONDARY: 'Inter, sans-serif',

  //-- Text
  CLR_TXT_PRIMARY: '#101828',
  CLR_TXT_SECONDARY: '#344054',
  CLR_TXT_TERTIARY: '#475467',
  CLR_TXT_BRAND_SECONDARY: '#367dc5',
  CLR_TXT_PLACEHOLDER: '#667085',
  CLR_TXT_HOVER_SECONDARY: '#182230',

  //-- Button
  CLR_BTN_BG_PRIMARY: '#3f8fd7',
  CLR_BTN_ERROR_BG_PRIMARY: '#d92d20',

  CLR_BTN_BORDER_PRIMARY: '#3f8fd7',
  CLR_BTN_BORDER_SECONDARY: '#d0d5dd',

  CLR_BTN_ERROR_BORDER_PRIMARY: '#d92d20',

  CLR_BTN_FG_PRIMARY: '#fff',
  CLR_BTN_FG_SECONDARY: '#344054',
  CLR_BTN_FG_TERTIARY: '#367dc5',

  //-- Background
  CLR_BG_SUCCESS_PRIMARY: '#ecfdf3',
  CLR_BG_BRAND_PRIMARY: '#e5f3fb',
  CLR_BG_BRAND_SOLID: '#3f8fd7',
  CLR_BG_OVERLAY: '#0c111d',
  CLR_BG_SECONDARY: '#f9fafb',
  CLR_BG_SECONDARY_SOLID: '#475467',
  CLR_BG_TERTIARY: '#f2f4f7',
  CLR_BG_WHITE: '#fff',

  //-- Height
  BUTTON_HEIGHT_MD: '38px',

  //-- Radius
  RADIUS_MD: '8px',

  BOX_SHADOW_XS: '#1018280D 0 1px 2px 0',

  CLR_BORDER_SECONDARY: '#eaecf0',

  CLR_TXT_PLACEHOLDER_SUBTTL: '#98a2b3',

  CLR_FG_QUARTERARY: '#667085',

  //-- Border
  CLR_BORDER_PRIMARY: '#d0d5dd',
  CLR_FG_SENARY: '#D0D5DD',

  // -- Migrate charts
  CLR_TXT_QUARTERARY: '#667085',
  CLR_TXT_ERROR_PRIMARY: '#D92D20',
  CLR_TXT_BRAND_PRIMARY: '#234F93',
  CLR_TXT_UTILITY_SUCCESS_700: '#067647',
  CLR_TXT_UTILITY_BLUE_700: '#175CD3',
  CLR_TXT_LINE_CHART_TEXT_GREEN: '#0E9283',
  CLR_BTN_FG_SUCCESS_PRIMARY: '#079455',
  CLR_BG_BLUE_LIGHT: '#f5fbff',
  CLR_BG_ERROR_PRIMARY: '#FEF3F2',
  CLR_BG_UTILITY_BLUE_50: '#EFF8FF',
  CLR_BORDER_ULTILITY_SUCCESS: '#ABEFC6',
  CLR_BORDER_UTILITY_BLUE_200: '#B2DDFF',
  CLR_UTILITY_WARNING_700: '#B54708',
  CLR_UTILITY_WARNING_50: '#FFFAEB',
  CLR_UTILITY_WARNING_200: '#FEDF89',
  CLR_CHART_SQUARE_RADAR_POINT: '#1570EF',
  CLR_CHART_SQUARE_RADAR_FILL: '#1570EF1A',
  CLR_CHART_SQUARE_RADAR_VALUE: '#175CD3',
  CLR_CHART_BAR_BLUE: '#2E90FA',
  CLR_CHART_BAR_TEAL: '#0BA5EC',
  CLR_CHART_BAR_GREEN: '#06AED4',
  CLR_CHART_RADAR_FILL_TEAL: '#0086C91A',
  CLR_CHART_RADAR_FILL_BORDER_TEAL: '#0086C9',
  CLR_CHART_RADAR_VALUE_TEAL: '#026AA2',
  CLR_CHART_RADAR_VALUE_BACKGROUND_TEAL: '#F0F9FF',
  CLR_CHART_RADAR_VALUE_BORDER_TEAL: '#B9E6FE',
  CLR_CHART_RADAR_FILL_GREEN: '#088AB21A',
  CLR_CHART_RADAR_FILL_BORDER_GREEN: '#0E7090',
  CLR_CHART_RADAR_VALUE_GREEN: '#0E7090',
  CLR_CHART_RADAR_VALUE_BACKGROUND_GREEN: '#ECFDFF',
  CLR_CHART_RADAR_VALUE_BORDER_GREEN: '#A5F0FC',
  CLR_CHART_LINE: '#15B79E',
  CLR_CHART_LINE_VALUE: '#107569',
  CLR_CHART_LINE_BORDER_VALUE: '#99F6E0',
  CLR_CHART_LINE_BACKGROUND_VALUE: '#F0FDF9',
  CLR_FG_QUINARY_HOVER: '#667085',
};
